
import java.awt.Cursor;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;
import javax.swing.JFileChooser;
import static javax.swing.JOptionPane.CANCEL_OPTION;
import static javax.swing.JOptionPane.YES_OPTION;
import static javax.swing.JOptionPane.showConfirmDialog;
import static javax.swing.JOptionPane.showInputDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.filechooser.FileNameExtensionFilter;


public class Ventana extends javax.swing.JFrame implements WindowListener{
    Lienzo l;
    BaseDeDatos ed;
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        ed = new BaseDeDatos();
        l = new Lienzo(jScrollPane1.getWidth(),jScrollPane1.getHeight(),ed.g);
        l.setLocation(0, 0);
        jScrollPane1.setViewportView(l);
        addWindowListener(this);
        setSize(1368,724);
        jMIGuardar.setEnabled(false);
        setResizable(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMINuevo = new javax.swing.JMenuItem();
        jMiAbrir = new javax.swing.JMenuItem();
        jMIGuardar = new javax.swing.JMenuItem();
        jMIGuardarC = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMIIVertice = new javax.swing.JMenuItem();
        jMIIArista = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMIEVertice = new javax.swing.JMenuItem();
        jMIEArista = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        MatrizDeAdyasencia = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenu5.setText("jMenu5");

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jScrollPane1MousePressed(evt);
            }
        });

        jMenuBar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuBar1MouseEntered(evt);
            }
        });

        jMenu1.setText("Archivo.");

        jMINuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMINuevo.setText("Nuevo");
        jMINuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMINuevoActionPerformed(evt);
            }
        });
        jMenu1.add(jMINuevo);

        jMiAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMiAbrir.setText("Abrir");
        jMiAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(jMiAbrir);

        jMIGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMIGuardar.setText("Guardar");
        jMIGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(jMIGuardar);

        jMIGuardarC.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMIGuardarC.setText("Guardar como...");
        jMIGuardarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIGuardarCActionPerformed(evt);
            }
        });
        jMenu1.add(jMIGuardarC);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edicion.");

        jMenu3.setText("Insertar");

        jMIIVertice.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMIIVertice.setText("Vertice");
        jMIIVertice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIIVerticeActionPerformed(evt);
            }
        });
        jMenu3.add(jMIIVertice);

        jMIIArista.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMIIArista.setText("Arista");
        jMIIArista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIIAristaActionPerformed(evt);
            }
        });
        jMenu3.add(jMIIArista);

        jMenu2.add(jMenu3);

        jMenu4.setText("Eliminar");

        jMIEVertice.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        jMIEVertice.setText("Vertice");
        jMIEVertice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIEVerticeActionPerformed(evt);
            }
        });
        jMenu4.add(jMIEVertice);

        jMIEArista.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMIEArista.setText("Arista");
        jMIEArista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIEAristaActionPerformed(evt);
            }
        });
        jMenu4.add(jMIEArista);

        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        jMenu7.setText("Informacion.");

        MatrizDeAdyasencia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        MatrizDeAdyasencia.setText("Buscar Camino...");
        MatrizDeAdyasencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatrizDeAdyasenciaActionPerformed(evt);
            }
        });
        jMenu7.add(MatrizDeAdyasencia);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Conjuntos...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Matriz de Adyacencia...");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Matriz de Incidencia...");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem3);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMiAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiAbrirActionPerformed
        if(ed.url != null){
            BaseDeDatos temp = new BaseDeDatos(ed.url);
        if(!ed.g.exactamenteIgualA(temp.g)){
            int opcion = showConfirmDialog(this,"Desea guardar cambios?");
            if(opcion == YES_OPTION){ed.guardar();}
            if(opcion == CANCEL_OPTION){return;}
                }
                }
        JFileChooser img=new javax.swing.JFileChooser(new File (".").getAbsolutePath ());
        img.setFileFilter(new FileNameExtensionFilter("EDD para el miniProyecto.","EDD_U4"));
        if(img.showOpenDialog(this)==JFileChooser.APPROVE_OPTION ){
            String formato = img.getSelectedFile().getPath();
            formato = formato.substring(formato.length()-6,formato.length());
            if(formato.equals("EDD_U4")){
            l.limpiarPantalla();
            l.vg.clear();
            ed = new BaseDeDatos(img.getSelectedFile().getPath());
            l.g = ed.g;
            l.nuevasVertices();
            l.repaint();
            jMIGuardar.setEnabled(true);
            }else{
                showMessageDialog(this,"Formato invalido!!!");
            }
        }
    }//GEN-LAST:event_jMiAbrirActionPerformed

    private void jMINuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMINuevoActionPerformed
        if(ed.url == null){return;}
            BaseDeDatos temp = new BaseDeDatos(ed.url);
        if(!ed.g.exactamenteIgualA(temp.g)){
            int opcion = showConfirmDialog(this,"Desea guardar cambios?");
            if(opcion == YES_OPTION){ed.guardar();}
            if(opcion == CANCEL_OPTION){return;}
                    }
        reIniciar();
    }//GEN-LAST:event_jMINuevoActionPerformed

    private void jMIIVerticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIIVerticeActionPerformed
    l.setCursor(new Cursor(Cursor.CROSSHAIR_CURSOR));
    l.pros = 1;
    }//GEN-LAST:event_jMIIVerticeActionPerformed

    private void jScrollPane1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MousePressed

    }//GEN-LAST:event_jScrollPane1MousePressed

    private void jMenuBar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MouseEntered

    }//GEN-LAST:event_jMenuBar1MouseEntered

    private void jMIIAristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIIAristaActionPerformed
    l.setCursor(new Cursor(Cursor.HAND_CURSOR));
    l.pros = 2;
    }//GEN-LAST:event_jMIIAristaActionPerformed

    private void jMIEAristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIEAristaActionPerformed
    l.setCursor(new Cursor(Cursor.HAND_CURSOR));
    l.pros = 4;
    }//GEN-LAST:event_jMIEAristaActionPerformed

    private void jMIEVerticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIEVerticeActionPerformed
    l.setCursor(new Cursor(Cursor.HAND_CURSOR));
    l.pros = 3;
    }//GEN-LAST:event_jMIEVerticeActionPerformed

    private void jMIGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIGuardarActionPerformed
        if(ed.url != null){ed.guardar();}
    }//GEN-LAST:event_jMIGuardarActionPerformed

    private void jMIGuardarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIGuardarCActionPerformed
        guardarComo();
        jMIGuardar.setEnabled(true);
    }//GEN-LAST:event_jMIGuardarCActionPerformed

    private void MatrizDeAdyasenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatrizDeAdyasenciaActionPerformed
        if(ed.g.estaVacio()){return;}
        Object org = showInputDialog(this,"Origen."),dest = showInputDialog(this,"Destino.");
        if(org == null || dest == null){return;}
        String path = ed.g.busquedaCamino(org,dest);
        if(path == null){showMessageDialog(this,"No exite ruta.");
            }else{showMessageDialog(this,"La ruta es:\n"+path);}
    }//GEN-LAST:event_MatrizDeAdyasenciaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if(ed.g.estaVacio()){return;}
        String m = ed.g.matrizDeAdyacencia();
        if(m == null){return;}
        showMessageDialog(this,m);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if(ed.g.estaVacio()){return;}
        String []m = ed.g.conjuntos();
        if(m == null){return;}
        String c="";
        for(int i = 0; i < m.length; i++){
            c +="{"+m[i]+"}\n";
        }
        showMessageDialog(this,"Conjuntos son:\n"+c);       
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    if(ed.g.estaVacio()){return;}
    String m = ed.g.matrizDeIncidencia();
        if(m == null){return;}
        showMessageDialog(this,m);
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    
    private void reIniciar(){
        ed = new BaseDeDatos();
        l.g = ed.g;
        l.repaint();
        l.limpiarPantalla();
        l.vg.clear();
        jMIGuardar.setEnabled(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MatrizDeAdyasencia;
    private javax.swing.JMenuItem jMIEArista;
    private javax.swing.JMenuItem jMIEVertice;
    private javax.swing.JMenuItem jMIGuardar;
    private javax.swing.JMenuItem jMIGuardarC;
    private javax.swing.JMenuItem jMIIArista;
    private javax.swing.JMenuItem jMIIVertice;
    private javax.swing.JMenuItem jMINuevo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMiAbrir;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

        private void guardarComo(){
        JFileChooser img=new javax.swing.JFileChooser(new File (".").getAbsolutePath ());
        img.setFileFilter(new FileNameExtensionFilter("EDD para el miniProyecto.","EDD_U4"));
        if(img.showSaveDialog(this) == JFileChooser.APPROVE_OPTION ){
            String path = img.getSelectedFile().getPath()+".EDD_U4";
            ed.url = path;
            ed.guardar();
        } 
    }
    
    @Override
    public void windowOpened(WindowEvent e) {}

    @Override
    public void windowClosing(WindowEvent e) {        
        if(ed.g.estaVacio() && ed.url == null){return;}
         if(ed.url != null){
            BaseDeDatos temp = new BaseDeDatos(ed.url);
            if(ed.g.exactamenteIgualA(temp.g)){return;}
         }
        if(showConfirmDialog(this,"Desea guardar cambios?") != YES_OPTION){return;}
        if(ed.url == null){
        guardarComo();
        }else{
            ed.guardar();
        }
    }

    @Override
    public void windowClosed(WindowEvent e) {}

    @Override
    public void windowIconified(WindowEvent e) {
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
    }

    @Override
    public void windowActivated(WindowEvent e) {
    l.acomodar();
    }

    @Override
    public void windowDeactivated(WindowEvent e) {}
}
